<?php
// ================================================
// ONE SERVER - HOMEPAGE ULTRA GASATA
// Ludopatia pura, animazioni assurde, GAS al 1000%!
// ================================================
?>

<!-- Include Ultra-Optimized CSS & JS -->
<link rel="stylesheet" href="<?php print $shop_url; ?>assets/css/shop-ultra-optimized.css?v=<?php echo time(); ?>">
<script src="<?php print $shop_url; ?>assets/js/shop-ultra-gasato.js?v=<?php echo time(); ?>"></script>

<!-- PARTICLES BACKGROUND (Auto-generated by JS) -->

<!-- ========================================
     HERO SECTION ULTRA-GASATO
     ======================================== -->
<div class="one-hero-bento" style="position: relative; overflow: hidden; min-height: 600px; background: linear-gradient(135deg, #0a0a0a 0%, #1a0000 100%); margin-bottom: 50px;">
    <!-- Animated Background -->
    <div class="one-hero-bg-anim" style="
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: url('<?php print $shop_url; ?>assets/img/hero-bg.jpg') center/cover;
        opacity: 0.3;
        animation: slowZoom 30s infinite alternate;
    "></div>

    <!-- Hero Content -->
    <div class="one-hero-content" style="position: relative; z-index: 10; text-align: center; padding: 100px 20px;">
        <span class="hero-tag animate-on-scroll" style="
            display: inline-block;
            background: linear-gradient(135deg, #ff0000, #ff6600);
            color: #fff;
            padding: 10px 30px;
            border-radius: 30px;
            font-weight: 900;
            text-transform: uppercase;
            letter-spacing: 2px;
            margin-bottom: 20px;
            box-shadow: 0 10px 30px rgba(255, 0, 0, 0.5);
            animation: pulse-glow 2s infinite;
        ">🔥 METIN2 ITEM SHOP EPICO 🔥</span>

        <h1 class="one-hero-title animate-on-scroll" style="
            font-size: 4rem;
            font-weight: 900;
            margin: 20px 0;
            line-height: 1.2;
        ">
            DOMINA IL <span class="text-gasato">SERVER</span>
        </h1>

        <p class="one-hero-subtitle animate-on-scroll" style="
            font-size: 1.5rem;
            color: #ccc;
            max-width: 700px;
            margin: 0 auto 40px auto;
            line-height: 1.6;
        ">
            ⚔️ Item LEGGENDARI • 💎 Costumi ESCLUSIVI • 🔮 Potenziamenti DEFINITIVI
        </p>

        <div class="one-hero-buttons animate-on-scroll" style="
            display: flex;
            gap: 20px;
            justify-content: center;
            flex-wrap: wrap;
        ">
            <a href="#shop-categories" class="gasato-btn">
                <i class="fa fa-th-large"></i> ESPLORA SHOP
            </a>
            <a href="<?php print $shop_url; ?>donations" class="gasato-btn" style="
                background: linear-gradient(135deg, #ffd700, #ffaa00);
                color: #000;
                border-color: #ff0000;
            ">
                <i class="fa fa-coins"></i> RICARICA MD
            </a>
        </div>

        <!-- Stats Bar GASATA -->
        <div class="stats-bar animate-on-scroll" style="
            display: flex;
            gap: 40px;
            justify-content: center;
            margin-top: 60px;
            flex-wrap: wrap;
        ">
            <div style="text-align: center;">
                <div style="font-size: 2.5rem; font-weight: 900; color: #ffd700;">500+</div>
                <div style="color: #888; text-transform: uppercase; font-size: 0.9rem;">Item Disponibili</div>
            </div>
            <div style="text-align: center;">
                <div style="font-size: 2.5rem; font-weight: 900; color: #ff0000;">15K+</div>
                <div style="color: #888; text-transform: uppercase; font-size: 0.9rem;">Giocatori Attivi</div>
            </div>
            <div style="text-align: center;">
                <div style="font-size: 2.5rem; font-weight: 900; color: #00ff00;">99.9%</div>
                <div style="color: #888; text-transform: uppercase; font-size: 0.9rem;">Soddisfazione</div>
            </div>
        </div>
    </div>
</div>

<!-- ========================================
     DEAL OF THE DAY - SUPER GASATO
     ======================================== -->
<?php
// Get highest discount item for "Deal of the Day"
$sth = $database->runQuerySqlite('SELECT * FROM item_shop_items WHERE discount > 0 ORDER BY discount DESC LIMIT 1');
$sth->execute();
$deal = $sth->fetch();

if($deal) {
    $deal_name = !$item_name_db ? get_item_name($deal['vnum']) : get_item_name_locale_name($deal['vnum']);
    $original_price = $deal['coins'];
    $final_price = round($deal['coins'] - ($deal['coins'] * $deal['discount'] / 100));
    $discount_end = date("Y-m-d H:i:s", $deal['discount_expire']);
?>
<div class="deal-of-day-container animate-on-scroll" style="
    background: linear-gradient(135deg, #1a0000 0%, #0a0a0a 100%);
    border: 3px solid #ffd700;
    border-radius: 20px;
    padding: 40px;
    margin: 0 20px 50px 20px;
    position: relative;
    overflow: hidden;
    box-shadow: 0 20px 60px rgba(255, 0, 0, 0.3), 0 0 50px rgba(255, 215, 0, 0.2);
">
    <span class="badge-hot" style="
        position: absolute;
        top: 20px;
        right: 20px;
        font-size: 1.2rem;
        padding: 12px 24px;
    ">🔥 HOT DEAL</span>

    <div style="text-align: center;">
        <h2 style="
            font-size: 2.5rem;
            margin: 0 0 10px 0;
            color: #ffd700;
            font-weight: 900;
            text-transform: uppercase;
            letter-spacing: 3px;
        ">⚡ AFFARE DEL GIORNO ⚡</h2>

        <p style="color: #888; font-size: 1.1rem; margin-bottom: 30px;">
            Sconto FOLLE del <span style="color: #ff0000; font-weight: 900; font-size: 1.5rem;">-<?php echo $deal['discount']; ?>%</span>!
        </p>

        <div style="display: flex; align-items: center; justify-content: center; gap: 40px; flex-wrap: wrap;">
            <div>
                <img src="<?php print $shop_url; ?>images/items/<?php print get_item_image($deal['vnum']); ?>.png"
                     style="max-height: 200px; filter: drop-shadow(0 10px 30px rgba(255, 215, 0, 0.5)); animation: float 3s infinite ease-in-out;">
            </div>

            <div style="text-align: left;">
                <h3 style="font-size: 2rem; color: #fff; margin: 0 0 20px 0;"><?php echo $deal_name; ?></h3>

                <div style="margin-bottom: 20px;">
                    <span style="
                        text-decoration: line-through;
                        color: #666;
                        font-size: 1.5rem;
                        margin-right: 15px;
                    "><?php echo $original_price; ?> MD</span>
                    <span style="
                        font-size: 3rem;
                        color: #ffd700;
                        font-weight: 900;
                    "><?php echo $final_price; ?> MD</span>
                </div>

                <div style="
                    background: rgba(255, 0, 0, 0.2);
                    border: 2px solid #ff0000;
                    padding: 15px 20px;
                    border-radius: 10px;
                    margin-bottom: 20px;
                ">
                    <div style="color: #ff0000; font-weight: 700; margin-bottom: 5px;">⏰ SCADE TRA:</div>
                    <div style="
                        font-size: 1.8rem;
                        color: #ffd700;
                        font-weight: 900;
                        font-family: monospace;
                    " data-countdown="<?php echo $discount_end; ?>"></div>
                </div>

                <a href="<?php print $shop_url.'item/'.$deal['id'].'/'; ?>" class="gasato-btn" style="
                    display: inline-block;
                    font-size: 1.2rem;
                    padding: 20px 60px;
                ">
                    <i class="fa fa-shopping-cart"></i> ACQUISTA ORA!
                </a>
            </div>
        </div>
    </div>
</div>
<?php } ?>

<!-- ========================================
     CATEGORIE BENTO GRID
     ======================================== -->
<div id="shop-categories" class="one-section-container animate-on-scroll" style="margin: 0 20px 50px 20px;">
    <div class="one-section-header" style="text-align: center; margin-bottom: 40px;">
        <h2 style="
            font-size: 2.5rem;
            font-weight: 900;
            margin: 0 0 10px 0;
        ">
            <i class="fa fa-layer-group" style="color: #ffd700;"></i>
            CATEGORIE EPICHE
        </h2>
        <p style="color: #888; font-size: 1.2rem;">Scegli il tuo destino, potenzia il tuo personaggio!</p>
    </div>

    <div class="one-bento-grid" style="
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        gap: 20px;
    ">
        <?php
        $categories = is_categories_list();
        $badges = ['NEW', 'HOT', 'LIMITED', 'EPICO', 'RARO'];

        foreach($categories as $idx => $cat) {
            $icon_path = "images/categories/" . $cat['id'] . ".png";
            $badge = $badges[array_rand($badges)];
        ?>

        <a href="<?php print $shop_url.'category/'.$cat['id'].'/'; ?>"
           class="item-card-gasato"
           style="
                display: block;
                text-decoration: none;
                padding: 30px;
                min-height: 200px;
                position: relative;
           ">
            <span class="badge-gasato"><?php echo $badge; ?></span>

            <div style="text-align: center;">
                <?php if(file_exists(__DIR__ . '/../../' . $icon_path)) { ?>
                    <img src="<?php print $shop_url . $icon_path; ?>?v=<?php echo time(); ?>"
                         alt="<?php echo $cat['name']; ?>"
                         style="max-width: 80px; margin-bottom: 15px; filter: drop-shadow(0 5px 15px rgba(255, 215, 0, 0.3));">
                <?php } else { ?>
                    <i class="fa fa-tag" style="font-size: 4rem; color: #ffd700; margin-bottom: 15px;"></i>
                <?php } ?>

                <h3 style="
                    color: #fff;
                    font-size: 1.3rem;
                    font-weight: 700;
                    text-transform: uppercase;
                    margin: 0;
                "><?php echo $cat['name']; ?></h3>

                <span style="
                    color: #ffd700;
                    font-size: 0.9rem;
                    margin-top: 10px;
                    display: inline-block;
                ">Esplora →</span>
            </div>
        </a>

        <?php } ?>
    </div>
</div>

<!-- ========================================
     NUOVI ARRIVI GASATI
     ======================================== -->
<div class="one-section-container animate-on-scroll" style="margin: 0 20px 50px 20px;">
    <div class="one-section-header" style="text-align: center; margin-bottom: 40px;">
        <h2 style="
            font-size: 2.5rem;
            font-weight: 900;
            margin: 0 0 10px 0;
        ">
            <i class="fa fa-bolt" style="color: #ffd700;"></i>
            NUOVI ARRIVI
        </h2>
        <p style="color: #888; font-size: 1.2rem;">Gli item più freschi appena aggiunti!</p>
    </div>

    <div style="
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
        gap: 20px;
    ">
        <?php
        try {
            $newest_items = is_get_newest_items(8);

            if(is_array($newest_items) && count($newest_items) > 0) {
                foreach($newest_items as $row) {
                    $item_name = !$item_name_db ? get_item_name($row['vnum']) : get_item_name_locale_name($row['vnum']);
                    $final_price = $row['discount'] > 0 ? round($row['coins'] - ($row['coins'] * $row['discount'] / 100)) : $row['coins'];
        ?>

        <a href="<?php print $shop_url.'item/'.$row['id'].'/'; ?>" class="item-card-gasato" style="
            display: block;
            text-decoration: none;
            padding: 20px;
            text-align: center;
        ">
            <?php if($row['discount'] > 0) { ?>
                <span class="badge-gasato">-<?php echo $row['discount']; ?>%</span>
            <?php } else { ?>
                <span class="badge-new">NEW</span>
            <?php } ?>

            <img src="<?php print $shop_url; ?>images/items/<?php print get_item_image($row['vnum']); ?>.png"
                 style="max-height: 120px; margin-bottom: 15px; filter: drop-shadow(0 5px 15px rgba(0, 0, 0, 0.5));">

            <h4 style="
                color: #fff;
                font-size: 1rem;
                margin: 0 0 10px 0;
                min-height: 40px;
            "><?php echo $item_name; ?></h4>

            <div style="
                font-size: 1.5rem;
                color: #ffd700;
                font-weight: 900;
            "><?php echo $final_price; ?> MD</div>
        </a>

        <?php
                }
            }
        } catch(Exception $e) { }
        ?>
    </div>
</div>

<!-- ========================================
     CTA FINALE GASATISSIMA
     ======================================== -->
<div class="cta-final animate-on-scroll" style="
    background: linear-gradient(135deg, #ff0000, #8a0000);
    padding: 60px 20px;
    text-align: center;
    border-radius: 20px;
    margin: 0 20px 50px 20px;
    box-shadow: 0 20px 60px rgba(255, 0, 0, 0.5);
">
    <h2 style="
        font-size: 3rem;
        color: #fff;
        font-weight: 900;
        margin: 0 0 20px 0;
        text-transform: uppercase;
    ">🎁 NON ASPETTARE!</h2>

    <p style="
        font-size: 1.5rem;
        color: #ffd700;
        margin: 0 0 30px 0;
    ">I tuoi item LEGGENDARI ti aspettano!</p>

    <a href="#shop-categories" class="gasato-btn" style="
        background: linear-gradient(135deg, #ffd700, #ffaa00);
        color: #000;
        font-size: 1.3rem;
        padding: 20px 60px;
    ">
        <i class="fa fa-rocket"></i> INIZIA SUBITO!
    </a>
</div>

<style>
@keyframes slowZoom {
    from { transform: scale(1); }
    to { transform: scale(1.1); }
}
</style>
